set shell := ["powershell", "-NoProfile", "-Command"]

default:
    @just --list

backend:
    $envFile = Join-Path (Get-Location) '.env.backend'; if (Test-Path $envFile) { Get-Content $envFile | ForEach-Object { $line = $_.Trim(); if ($line -and -not $line.StartsWith('#')) { $parts = $line -split '=', 2; if ($parts.Length -eq 2 -and -not [string]::IsNullOrWhiteSpace($parts[0])) { [System.Environment]::SetEnvironmentVariable($parts[0].Trim(), $parts[1].Trim().Trim('"'), 'Process') } } } }; $bindHost = if ($env:BIND_HOST) { $env:BIND_HOST } else { "0.0.0.0" }; $backendPort = if ($env:BACKEND_PORT) { $env:BACKEND_PORT } else { "8081" }; $dataDir = if ($env:ASSIGN_SERVER_DATA_DIR) { $env:ASSIGN_SERVER_DATA_DIR } else { "assign-server-data" }; $dbUrl = if ($env:ASSIGN_DB_URL) { $env:ASSIGN_DB_URL } else { "jdbc:mysql://localhost:3306/exam_scheduler?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8" }; $dbUser = if ($env:ASSIGN_DB_USER) { $env:ASSIGN_DB_USER } else { "root" }; $dbPassword = if ($env:ASSIGN_DB_PASSWORD) { $env:ASSIGN_DB_PASSWORD } else { "" }; Set-Location assign-server; & mvn '-q' 'clean' 'compile' "-Dassign.dataDir=$dataDir" "-Dassign.dbUrl=$dbUrl" "-Dassign.dbUser=$dbUser" "-Dassign.dbPassword=$dbPassword"; & mvn 'jetty:run' "-Djetty.http.host=$bindHost" "-Djetty.http.port=$backendPort" "-Dassign.dataDir=$dataDir" "-Dassign.dbUrl=$dbUrl" "-Dassign.dbUser=$dbUser" "-Dassign.dbPassword=$dbPassword"

frontend:
    $envFile = Join-Path (Get-Location) '.env.frontend'; if (Test-Path $envFile) { Get-Content $envFile | ForEach-Object { $line = $_.Trim(); if ($line -and -not $line.StartsWith('#')) { $parts = $line -split '=', 2; if ($parts.Length -eq 2 -and -not [string]::IsNullOrWhiteSpace($parts[0])) { [System.Environment]::SetEnvironmentVariable($parts[0].Trim(), $parts[1].Trim().Trim('"'), 'Process') } } } }; $bindHost = if ($env:BIND_HOST) { $env:BIND_HOST } else { "0.0.0.0" }; $frontendPort = if ($env:FRONTEND_PORT) { $env:FRONTEND_PORT } else { "8080" }; $backendPort = if ($env:BACKEND_PORT) { $env:BACKEND_PORT } else { "8081" }; $serverBaseUrl = if ($env:SERVER_BASE_URL) { $env:SERVER_BASE_URL } else { "http://localhost:$backendPort/assign-server" }; Set-Location client-web; & mvn '-q' 'clean' 'compile' "-DserverBaseUrl=$serverBaseUrl"; & mvn 'jetty:run' "-Djetty.http.host=$bindHost" "-Djetty.http.port=$frontendPort" "-DserverBaseUrl=$serverBaseUrl"

test:
    $envFile = Join-Path (Get-Location) '.env.backend'; if (Test-Path $envFile) { Get-Content $envFile | ForEach-Object { $line = $_.Trim(); if ($line -and -not $line.StartsWith('#')) { $parts = $line -split '=', 2; if ($parts.Length -eq 2 -and -not [string]::IsNullOrWhiteSpace($parts[0])) { [System.Environment]::SetEnvironmentVariable($parts[0].Trim(), $parts[1].Trim().Trim('"'), 'Process') } } } }; Set-Location assign-server; mvn test

dev:
    @('.env.backend', '.env.frontend') | ForEach-Object { $envFile = Join-Path (Get-Location) $_; if (Test-Path $envFile) { Get-Content $envFile | ForEach-Object { $line = $_.Trim(); if ($line -and -not $line.StartsWith('#')) { $parts = $line -split '=', 2; if ($parts.Length -eq 2 -and -not [string]::IsNullOrWhiteSpace($parts[0])) { [System.Environment]::SetEnvironmentVariable($parts[0].Trim(), $parts[1].Trim().Trim('"'), 'Process') } } } } }; if (-not (Get-Command watchexec -ErrorAction SilentlyContinue)) { throw "Missing 'watchexec'. Install it first." }; $bindHost = if ($env:BIND_HOST) { $env:BIND_HOST } else { "0.0.0.0" }; $backendPort = if ($env:BACKEND_PORT) { $env:BACKEND_PORT } else { "8081" }; $frontendPort = if ($env:FRONTEND_PORT) { $env:FRONTEND_PORT } else { "8080" }; $serverBaseUrl = if ($env:SERVER_BASE_URL) { $env:SERVER_BASE_URL } else { "http://localhost:$backendPort/assign-server" }; $dataDir = if ($env:ASSIGN_SERVER_DATA_DIR) { $env:ASSIGN_SERVER_DATA_DIR } else { "assign-server-data" }; $dbUrl = if ($env:ASSIGN_DB_URL) { $env:ASSIGN_DB_URL } else { "jdbc:mysql://localhost:3306/exam_scheduler?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8" }; $dbUser = if ($env:ASSIGN_DB_USER) { $env:ASSIGN_DB_USER } else { "root" }; $dbPassword = if ($env:ASSIGN_DB_PASSWORD) { $env:ASSIGN_DB_PASSWORD } else { "" }; watchexec --restart --watch assign-server/src --watch client-web/src --watch pom.xml --watch assign-server/pom.xml --watch client-web/pom.xml --exts java,jsp,xml,properties -- "& { Start-Job { Set-Location assign-server; & mvn '-q' 'clean' 'compile' ""-Dassign.dataDir=$dataDir"" ""-Dassign.dbUrl=$dbUrl"" ""-Dassign.dbUser=$dbUser"" ""-Dassign.dbPassword=$dbPassword""; & mvn 'jetty:run' ""-Djetty.http.host=$bindHost"" ""-Djetty.http.port=$backendPort"" ""-Dassign.dataDir=$dataDir"" ""-Dassign.dbUrl=$dbUrl"" ""-Dassign.dbUser=$dbUser"" ""-Dassign.dbPassword=$dbPassword"" } | Out-Null; Start-Job { Set-Location client-web; & mvn '-q' 'clean' 'compile' ""-DserverBaseUrl=$serverBaseUrl""; & mvn 'jetty:run' ""-Djetty.http.host=$bindHost"" ""-Djetty.http.port=$frontendPort"" ""-DserverBaseUrl=$serverBaseUrl"" } | Out-Null; Wait-Job * }"

deploy-server:
    ./scripts/deploy-server-lan.sh

deploy-client:
    ./scripts/deploy-client-lan.sh
